apiVersion: v1
kind: Service
metadata:
  name: bitcoin-testnet-svc
  namespace: default
  annotations:
spec:
  selector:
    app: bitcoin-testnet-app
  ports:
  - name: rpc
    port: 18332
    protocol: TCP
    targetPort: 18332
  - name: zmq
    port: 28332
    protocol: TCP
    targetPort: 28332
  type: ClusterIP