apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-testnet-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bitcoin-testnet-app
  serviceName: bitcoin-testnet-svc
  template:
    metadata:
      labels:
        app: bitcoin-testnet-app
    spec:
      volumes:
      - name: bitcoin-testnet-conf
        configMap:
          name: bitcoin-testnet-conf
          items:
          - key: entrypoint.sh
            path: entrypoint.sh
            mode: 365
      containers:
      - env:
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              key: rpcuser
              name: bitcoin-secret
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rpcpass
              name: bitcoin-secret
        image: zquestz/bitcoin-abc
        imagePullPolicy: Always
        name: bitcoin
        ports:
          - containerPort: 18332
          - containerPort: 18333
          - containerPort: 28332
        command: ["/entrypoint.sh"]
        args: ["bitcoind"]
        resources:
          requests:
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: bitcoin-testnet-pvc
        - mountPath: /entrypoint.sh
          name: bitcoin-testnet-conf
          subPath: entrypoint.sh
  volumeClaimTemplates:
  - metadata:
      name: bitcoin-testnet-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 60Gi