apiVersion: v1
kind: Service
metadata:
  name: slpdb-svc
  namespace: default
spec:
  selector:
    app: slpdb-app
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  type: ClusterIP