apiVersion: apps/v1
kind: Deployment
metadata:
  name: slpserve-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slpserve-app
  template:
    metadata:
      labels:
        app: slpserve-app
    spec:
      containers:
      - name: slpserve
        image: spendbch/slpserve:latest
        ports:
          - containerPort: 3000
        env:
        - name: db_url
          value: "mongodb://slpdb-svc.default.svc.cluster.local:27017"