apiVersion: v1
kind: ConfigMap
metadata:
  name: slpserve-nginx-conf
data:
  default: |
    upstream app {
      server localhost:3000;
      keepalive 1024;
    }

    server {
      listen 443 ssl default_server;

      server_name _;

      include /config/nginx/ssl.conf;

      location / {
        proxy_pass http://app;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }