apiVersion: v1
kind: Service
metadata:
  name: slpserve-svc
  namespace: default
spec:
  selector:
    app: slpserve-app
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: NodePort