apiVersion: v1
kind: Service
metadata:
  name: slpserve-testnet-svc
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: slpserve-testnet-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: debug
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer