apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wormhole-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wormhole-app
  serviceName: wormhole-svc
  template:
    metadata:
      labels:
        app: wormhole-app
    spec:
      volumes:
      - name: wormhole-conf
        configMap:
          name: wormhole-conf
          items:
          - key: entrypoint.sh
            path: entrypoint.sh
            mode: 365
      containers:
      - env:
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              key: rpcuser
              name: bitcoin-secret
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rpcpass
              name: bitcoin-secret
        image: zquestz/wormhole
        imagePullPolicy: Always
        name: bitcoin
        ports:
          - containerPort: 8332
          - containerPort: 8333
          - containerPort: 28332
        command: ["/entrypoint.sh"]
        args: ["wormholed"]
        resources:
          requests:
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: wormhole-pvc
        - mountPath: /entrypoint.sh
          name: wormhole-conf
          subPath: entrypoint.sh
  volumeClaimTemplates:
  - metadata:
      name: wormhole-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 220Gi